name: Bot CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - 'bot/**'
      - '.github/workflows/bot.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./bot
        file: ./bot/Dockerfile
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ghcr.io/davidarico/stinkbot:latest
